---
title: "Regular Expressions"
author: "Izolda Fetko"
date: "1/28/2019"
output:
  html_document:
    df_print: paged
---

### RegEx Methods
Install library `strings`

```{r echo=FALSE, warning=FALSE, message = FALSE}
library(stringr)
library(htmlwidgets)
library(tidyverse)
library(readr)
```

```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

import text file
```{r}
text <- read_lines("C:/Users/Justin/Downloads/scraping.txt")
text[1:3]
```

extract string - test
```{r}
str_extract_all(text, "[0-9]+")[[1]] # list 
```

build regex
`[a-zA-Z]+\s[0-9][0-9],\s[0-9]{4}`

```{r}
dates <- regex("
[a-zA-Z]+
\\s
[0-9]
[0-9]
,
\\s
[0-9]{4}
", comments = TRUE)
```
Match regex - print all
```{r}
str_match(text, dates)
```
Print only dates
```{r}
results = str_match(text, dates)
for (i in results){
  if (!is.na(i)){
    print(i)
  }
}

```
Quiz Questions - Create vector from the text of only dates
```{r}
x<-c("March 11, 2016", "March 11, 2016", "February 12, 2016", "March 25, 2016")
```

Use str_replace to change date format

```{r}
replacement <- strftime(strptime(x, "%B %d, %Y"), "%m/%d/%Y")
str_replace(x,dates, replacement)
```